package: aceeditor
version: 1.3.0
author: 'Friends Of REDAXO'
supportpage: 'https://github.com/FriendsOfREDAXO/aceeditor'

pages:
  system/aceeditor: { title: translate:aceeditor_title }

pjax: false

requires:
  php:
    version: '>=7.4, <8.3' # benötigt mindestens PHP 7.4
  redaxo: '^5.8' # benötigt mindestens REDAXO 5.8

default_config:
  active: ''
  selectors: 'textarea.rex-code, textarea.rex-js-code, textarea.aceeditor, textarea.codemirror'
  theme: 'eclipse'
  darktheme: 'dracula'
  options: "{\r\n    \"showLineNumbers\": true,\r\n    \"showGutter\": true,\r\n    \"showInvisibles\": false,\r\n    \"fontSize\": 15,\r\n    \"mode\": \"ace\/mode\/php\",\r\n    \"displayIndentGuides\": false,\r\n    \"highlightIndentGuides\": false,\r\n    \"customScrollbar\": true,\r\n    \"enableBasicAutocompletion\": false,\r\n    \"enableLiveAutocompletion\": false,\r\n    \"enableSnippets\": false\r\n}"
